# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 1.16.x ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Unzip built zip
      run:   |
             if [ "$RUNNER_OS" == "Linux" ]; then
                cd builds/libs
                unzip "*.zip" -d build/libs/
             elif [ "$RUNNER_OS" == "Windows" ]; then
                7z e *.zip -oc:\build\libs
             else
                echo "Haven't implememted anything for $RUNNER_OS yet."
             fi
      shell: bash
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
       path: builds/libs/*.jar
