# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew buildAll
   
      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: build
          path: build/libs
          
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          game_endpoint: minecraft
          file_path: build/libs
          changelog: Automatic github release
          display_name: IBE_Editor_Github
          game_versions: minecraft-1.16:1.16.5,Fabric,Java 8,minecraft-1.17,Fabric,Java 8
          release_type: alpha
